// templates/vue/src/pages/detail/[id].vue
<script setup lang="ts">
import { todosStore } from '~/stores'

const route = useRoute()
const id = Number(route.params.id as string)

const store = todosStore()
let done = false
let todo = store.todos.find(todo => todo.id === id)
if (!todo) {
  done = true
  todo = store.doneTodos.find(todo => todo.id === id)
}

type ActionType = 'Delete' | 'Done' | 'Back'
const actions: ActionType[] = done ? ['Delete', 'Back'] : ['Done', 'Delete', 'Back']

const router = useRouter()

const back = () => router.back()

const actionHandle = (action: ActionType) => {
  switch (action) {
    case 'Done':
      store.todoDone(todo!.id, !done)
      break
    case 'Delete':
      store.deleteTodo(todo!.id, done)
      break
  }
  back()
}
</script>

<template>
  <div font-sans flex="~ col" items-center text="gray-700 dark:gray-200">
    <div text-3xl pb-10>
      Todo
    </div>
    <template v-if="todo">
      <div text-xl>
        {{ todo.content }}
      </div>
      <div mt-20>
        <button
          v-for="action in actions"
          :key="action"
          p="x-3 y-2"
          opacity="70 hover:100"
          @click="actionHandle(action)"
        >
          {{ action }}
        </button>
      </div>
    </template>

    <template v-else>
      <div text-xl>
        Not Found
      </div>
      <button
        mt-20
        p="x-3 y-2"
        opacity="70 hover:100"
        @click="back"
      >
        Back
      </button>
    </template>
  </div>
</template>

<style scope></style>

// templates/react/src/pages/detail/[id].tsx
import { useStores } from '~/stores'

type ActionType = 'Delete' | 'Done' | 'Back'

export default function Detail() {
  const navigate = useNavigate()
  const params = useParams()
  const { todoListStore } = useStores()
  const { todos, deleteTodo, todoDone } = todoListStore
  const todo = todos.find(t => t.id === Number(params.id))

  if (todo) {
    const actions: ActionType[] = todo?.done ? ['Delete', 'Back'] : ['Done', 'Delete', 'Back']

    const actionHandle = (action: ActionType) => {
      switch (action) {
        case 'Done':
          todoDone(todo!.id)
          break
        case 'Delete':
          deleteTodo(todo!.id)
          navigate(-1)
          break
        case 'Back':
          navigate(-1)
          break
      }
    }
    return (
      <div className="flex flex-col justify-center items-center">
        <div className="text-3xl pb-10">Todo</div>

        <div className="text-xl">{todo?.content}</div>
        <div className="mt-20">
          {
            actions.map(action => (
              <button
                className="px-3 py-2 opacity-70 hover:opacity-100"
                key={action}
                onClick={() => actionHandle(action)}
              >
                {action}
              </button>
            ))
          }
        </div>
      </div>
    )
  }
  else {
    return (
      <div className="flex flex-col justify-center items-center">
        <div className="text-3xl pb-10">Todo</div>
        <div className="text-xl">Not Found</div>
        <button
          className="mt-20 px-3 py-2 opacity-70 hover:opacity-100"
          onClick={() => navigate(-1)}
        >Back</button>
      </div>
    )
  }
}
